### ISSUE TITLE
Cannot run due to missing nativemidisystem

### ISSUE THREAD

**Issue by pft** [khremeviuc1004/NanoPAD2ControllerEditor#1]
Hi there,

When I try to run the application, I get the following exception:

```
$> java -Djava.library.path=./target -jar ./target/NanoPAD2Controller2-1.0-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: no nativemidisystem in java.library.path: ./target
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at au.com.pwcu.nanopad2controller.appn.NanoPad2Controller.<clinit>(NanoPad2Controller.java:20)
```

**Comment by pft** [comment]
Resolved: Needed to run https://github.com/khremeviuc1004/NanoPAD2ControllerEditor#c-java-jni-dynamic-library-build first.

That complained about missing jni.h, which I resolved by installiing openjdk-18-jdk (on Ubuntu).
